# Generated by Django 6.1.1 on 2026-09-22 11:57

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        ("attendance", "0001_initial"),
        ("student", "0001_initial"),
        ("teacher", "0002_teachernotemodel_attendance_session_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان تکلیف")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="زمان تعیین تکلیف"
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="مهلت انجام"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("submitted", "تحویل داده شده"),
                            ("reviewed", "بررسی شده"),
                            ("late", "با تأخیر"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "attendance_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="attendance.attendancesessionmodel",
                        verbose_name="جلسه",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="academic.classroommodel",
                        verbose_name="کلاس",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="academic.subjectmodel",
                        verbose_name="درس",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="teacher.teachermodel",
                        verbose_name="معلم",
                    ),
                ),
            ],
            options={
                "verbose_name": "تکلیف",
                "verbose_name_plural": "تکالیف",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DailyGradeModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="نمره"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "attendance_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_grades",
                        to="attendance.attendancesessionmodel",
                        verbose_name="جلسه حضور و غیاب",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_grades",
                        to="academic.classroommodel",
                        verbose_name="کلاس",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_grades",
                        to="student.studentmodel",
                        verbose_name="دانش\u200cآموز",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_grades",
                        to="academic.subjectmodel",
                        verbose_name="درس",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_grades",
                        to="teacher.teachermodel",
                        verbose_name="معلم",
                    ),
                ),
            ],
            options={
                "verbose_name": "نمره روزانه",
                "verbose_name_plural": "نمرات روزانه",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="EducationalActivityModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("teaching", "تدریس"),
                            ("review", "مرور"),
                            ("exercise", "حل تمرین"),
                            ("questioning", "پرسش"),
                            ("group_work", "کار گروهی"),
                            ("other", "سایر"),
                        ],
                        max_length=30,
                        verbose_name="نوع فعالیت",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان فعالیت"),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "attendance_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="educational_activities",
                        to="attendance.attendancesessionmodel",
                        verbose_name="جلسه",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="educational_activities",
                        to="academic.classroommodel",
                        verbose_name="کلاس",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="educational_activities",
                        to="academic.subjectmodel",
                        verbose_name="درس",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="educational_activities",
                        to="teacher.teachermodel",
                        verbose_name="معلم",
                    ),
                ),
            ],
            options={
                "verbose_name": "فعالیت آموزشی",
                "verbose_name_plural": "فعالیت\u200cهای آموزشی",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ExamModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان امتحان"),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("exam_date", models.DateField(verbose_name="تاریخ امتحان")),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=5,
                        verbose_name="نمره کل",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="مدت امتحان (دقیقه)"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="اعلام نتایج"),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exams",
                        to="academic.classroommodel",
                        verbose_name="کلاس",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exams",
                        to="academic.subjectmodel",
                        verbose_name="درس",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exams",
                        to="teacher.teachermodel",
                        verbose_name="معلم",
                    ),
                ),
            ],
            options={
                "verbose_name": "امتحان",
                "verbose_name_plural": "امتحانات",
                "ordering": ("-exam_date",),
            },
        ),
        migrations.CreateModel(
            name="ExamResultModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="نمره"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="education.exammodel",
                        verbose_name="امتحان",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_results",
                        to="student.studentmodel",
                        verbose_name="دانش\u200cآموز",
                    ),
                ),
            ],
            options={
                "verbose_name": "نتیجه امتحان",
                "verbose_name_plural": "نتایج امتحانات",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("exam", "student"),
                        name="unique_exam_result_per_student",
                    )
                ],
            },
        ),
    ]
