# Generated by Django 6.1.1 on 2026-09-21 11:11

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                (
                    "national_id",
                    models.CharField(max_length=10, unique=True, verbose_name="کد ملی"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "فعال"),
                            ("inactive", "غیرفعال"),
                            ("on_leave", "در مرخصی"),
                            ("suspended", "معلق"),
                            ("terminated", "پایان همکاری"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="وضعیت همکاری",
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "تمام\u200cوقت"),
                            ("part_time", "پاره\u200cوقت"),
                            ("contract", "قراردادی"),
                            ("temporary", "موقت"),
                        ],
                        default="full_time",
                        max_length=20,
                        verbose_name="نوع همکاری",
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="مدرک تحصیلی"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=128, verbose_name="تخصص"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حساب کاربری",
                    ),
                ),
            ],
            options={
                "verbose_name": "معلم",
                "verbose_name_plural": "معلمان",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="EmploymentRecordModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "تمام\u200cوقت"),
                            ("part_time", "پاره\u200cوقت"),
                            ("contract", "قراردادی"),
                            ("temporary", "موقت"),
                        ],
                        max_length=20,
                        verbose_name="نوع همکاری",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاریخ شروع")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ پایان"),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employment_records",
                        to="teacher.teachermodel",
                        verbose_name="معلم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سابقه همکاری",
                "verbose_name_plural": "سوابق همکاری",
                "ordering": ("-start_date",),
            },
        ),
        migrations.CreateModel(
            name="TeacherNoteModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("content", models.TextField(verbose_name="متن یادداشت")),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="teacher.teachermodel",
                        verbose_name="معلم",
                    ),
                ),
            ],
            options={
                "verbose_name": "یادداشت معلم",
                "verbose_name_plural": "یادداشت\u200cهای معلمان",
                "ordering": ("-created_at",),
            },
        ),
    ]
