# Generated by Django 6.1.1 on 2026-09-22 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachernotemodel",
            name="attendance_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_notes",
                to="attendance.attendancesessionmodel",
                verbose_name="جلسه",
            ),
        ),
        migrations.AddField(
            model_name="teachernotemodel",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="انجام شده"),
        ),
    ]
