# Generated by Django 6.1.1 on 2026-10-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_teachernotemodel_attendance_session_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmploymentRecordModel",
        ),
    ]
