# Generated by Django 6.1.1 on 2026-09-22 11:25

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        ("student", "0001_initial"),
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSessionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                (
                    "session_number",
                    models.PositiveSmallIntegerField(verbose_name="شماره جلسه"),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_sessions",
                        to="academic.classroommodel",
                        verbose_name="کلاس",
                    ),
                ),
                (
                    "schedule_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_sessions",
                        to="academic.schedulesessionmodel",
                        verbose_name="جلسه برنامه هفتگی",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسه حضور و غیاب",
                "verbose_name_plural": "جلسات حضور و غیاب",
                "ordering": ("-date", "session_number"),
            },
        ),
        migrations.CreateModel(
            name="StaffAttendanceModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "حاضر"),
                            ("absent", "غایب"),
                            ("late", "تاخیر"),
                            ("leave", "مرخصی"),
                        ],
                        default="present",
                        max_length=20,
                        verbose_name="وضعیت حضور",
                    ),
                ),
                (
                    "arrival_time",
                    models.TimeField(blank=True, null=True, verbose_name="زمان ورود"),
                ),
                (
                    "departure_time",
                    models.TimeField(blank=True, null=True, verbose_name="زمان خروج"),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendances",
                        to="teacher.teachermodel",
                        verbose_name="معلم",
                    ),
                ),
            ],
            options={
                "verbose_name": "حضور و غیاب معلم",
                "verbose_name_plural": "حضور و غیاب معلمان",
                "ordering": ("-date",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("teacher", "date"),
                        name="unique_teacher_attendance_per_day",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentAttendanceModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "حاضر"),
                            ("absent", "غایب"),
                            ("late", "تاخیر"),
                            ("excused", "غیبت موجه"),
                        ],
                        default="present",
                        max_length=20,
                        verbose_name="وضعیت حضور",
                    ),
                ),
                (
                    "arrival_time",
                    models.TimeField(blank=True, null=True, verbose_name="زمان ورود"),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_attendances",
                        to="attendance.attendancesessionmodel",
                        verbose_name="جلسه حضور و غیاب",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendances",
                        to="student.studentmodel",
                        verbose_name="دانش\u200cآموز",
                    ),
                ),
            ],
            options={
                "verbose_name": "حضور و غیاب دانش\u200cآموز",
                "verbose_name_plural": "حضور و غیاب دانش\u200cآموزان",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "student"),
                        name="unique_student_attendance_per_session",
                    )
                ],
            },
        ),
    ]
