# Generated by Django 6.1.1 on 2026-09-21 11:00

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                (
                    "national_id",
                    models.CharField(max_length=10, unique=True, verbose_name="کد ملی"),
                ),
                (
                    "father_name",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="نام پدر"
                    ),
                ),
                (
                    "parent_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        verbose_name="شماره تماس اولیاء",
                    ),
                ),
                (
                    "birth_date",
                    models.CharField(
                        blank=True, max_length=12, null=True, verbose_name="تاریخ تولد"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="آدرس")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "فعال"),
                            ("inactive", "غیرفعال"),
                            ("graduated", "فارغ\u200cالتحصیل"),
                            ("transferred", "انتقال\u200cیافته"),
                            ("suspended", "معلق"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="وضعیت دانش\u200cآموز",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ ثبت \u200cنام"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حساب کاربری",
                    ),
                ),
            ],
            options={
                "verbose_name": "دانش\u200cآموز",
                "verbose_name_plural": "دانش\u200cآموزان",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="StudentNoteModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("content", models.TextField(verbose_name="متن یادداشت")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="student.studentmodel",
                        verbose_name="دانش\u200cآموز",
                    ),
                ),
            ],
            options={
                "verbose_name": "یادداشت دانش\u200cآموز",
                "verbose_name_plural": "یادداشت\u200cهای دانش\u200cآموزان",
                "ordering": ("-created_at",),
            },
        ),
    ]
