# Generated by Django 6.1.1 on 2026-09-27 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentmodel",
            name="enrollment_date",
        ),
    ]
