# Generated by Django 6.1.1 on 2026-09-22 12:31

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        ("student", "0001_initial"),
        ("teacher", "0002_teachernotemodel_attendance_session_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolExpenseModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان هزینه")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("salary", "حقوق"),
                            ("equipment", "تجهیزات"),
                            ("maintenance", "تعمیرات"),
                            ("utilities", "قبوض و خدمات"),
                            ("education", "آموزشی"),
                            ("office", "اداری"),
                            ("transportation", "حمل\u200cونقل"),
                            ("other", "سایر"),
                        ],
                        max_length=30,
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=14, verbose_name="مبلغ"
                    ),
                ),
                ("expense_date", models.DateField(verbose_name="تاریخ هزینه")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="شماره رسید"
                    ),
                ),
            ],
            options={
                "verbose_name": "هزینه مدرسه",
                "verbose_name_plural": "هزینه\u200cهای مدرسه",
                "ordering": ("-expense_date",),
            },
        ),
        migrations.CreateModel(
            name="StaffSalaryModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="سال")),
                ("month", models.PositiveSmallIntegerField(verbose_name="ماه")),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=14, verbose_name="حقوق پایه"
                    ),
                ),
                (
                    "bonus_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=14,
                        verbose_name="پاداش و اضافه پرداخت",
                    ),
                ),
                (
                    "deduction_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=14,
                        verbose_name="کسورات",
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=14, verbose_name="حقوق نهایی"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پرداخت"),
                            ("partial", "پرداخت ناقص"),
                            ("paid", "پرداخت شده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_salaries",
                        to="academic.academicyearmodel",
                        verbose_name="سال تحصیلی",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salaries",
                        to="teacher.teachermodel",
                        verbose_name="معلم",
                    ),
                ),
            ],
            options={
                "verbose_name": "حقوق معلم",
                "verbose_name_plural": "حقوق معلمان",
                "ordering": ("-year", "-month"),
            },
        ),
        migrations.CreateModel(
            name="SalaryPaymentModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=14, verbose_name="مبلغ پرداخت"
                    ),
                ),
                ("payment_date", models.DateTimeField(verbose_name="تاریخ پرداخت")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "نقدی"),
                            ("card_to_card", "کارت به کارت"),
                            ("gateway", "درگاه پرداخت"),
                        ],
                        max_length=20,
                        verbose_name="روش پرداخت",
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="کد پیگیری"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "salary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="finance.staffsalarymodel",
                        verbose_name="حقوق",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت حقوق",
                "verbose_name_plural": "پرداخت\u200cهای حقوق",
                "ordering": ("-payment_date",),
            },
        ),
        migrations.CreateModel(
            name="TuitionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=14, verbose_name="مبلغ شهریه"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=14, verbose_name="تخفیف"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پرداخت"),
                            ("partial", "پرداخت ناقص"),
                            ("paid", "تسویه شده"),
                            ("cancelled", "لغو شده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tuitions",
                        to="academic.academicyearmodel",
                        verbose_name="سال تحصیلی",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tuitions",
                        to="student.studentmodel",
                        verbose_name="دانش\u200cآموز",
                    ),
                ),
            ],
            options={
                "verbose_name": "شهریه",
                "verbose_name_plural": "شهریه ها",
            },
        ),
        migrations.CreateModel(
            name="TuitionInstallmentModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                (
                    "installment_number",
                    models.PositiveSmallIntegerField(verbose_name="شماره قسط"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=14, verbose_name="مبلغ قسط"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="سررسید"),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "tuition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="finance.tuitionmodel",
                        verbose_name="شهریه",
                    ),
                ),
            ],
            options={
                "verbose_name": "قسط شهریه",
                "verbose_name_plural": "اقساط شهریه",
                "ordering": ("installment_number",),
            },
        ),
        migrations.CreateModel(
            name="PaymentRecordModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=14, verbose_name="مبلغ پرداخت"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "نقدی"),
                            ("card_to_card", "کارت به کارت"),
                            ("gateway", "درگاه پرداخت"),
                        ],
                        max_length=20,
                        verbose_name="روش پرداخت",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("paid", "پرداخت شده"),
                            ("failed", "ناموفق"),
                            ("cancelled", "لغو شده"),
                        ],
                        default="paid",
                        max_length=20,
                        verbose_name="وضعیت پرداخت",
                    ),
                ),
                ("payment_date", models.DateTimeField(verbose_name="تاریخ پرداخت")),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="کد پیگیری"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_records",
                        to="student.studentmodel",
                        verbose_name="دانش\u200cآموز",
                    ),
                ),
                (
                    "installment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="finance.tuitioninstallmentmodel",
                        verbose_name="قسط",
                    ),
                ),
                (
                    "tuition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="finance.tuitionmodel",
                        verbose_name="شهریه",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت شهریه",
                "verbose_name_plural": "پرداخت های شهریه",
            },
        ),
        migrations.AddConstraint(
            model_name="staffsalarymodel",
            constraint=models.UniqueConstraint(
                fields=("teacher", "year", "month"),
                name="unique_teacher_salary_per_month",
            ),
        ),
        migrations.AddConstraint(
            model_name="tuitioninstallmentmodel",
            constraint=models.UniqueConstraint(
                fields=("tuition", "installment_number"),
                name="unique_tuition_installment",
            ),
        ),
    ]
