# Generated by Django 6.1.1 on 2026-09-21 11:47

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("student", "0001_initial"),
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYearModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="عنوان سال تحصیلی"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاریخ شروع")),
                ("end_date", models.DateField(verbose_name="تاریخ پایان")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "در حال برنامه\u200cریزی"),
                            ("active", "فعال"),
                            ("completed", "پایان\u200cیافته"),
                            ("archived", "بایگانی\u200cشده"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
            ],
            options={
                "verbose_name": "سال تحصیلی",
                "verbose_name_plural": "سال\u200cهای تحصیلی",
                "ordering": ("-start_date",),
            },
        ),
        migrations.CreateModel(
            name="GradeModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام پایه")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="کد پایه"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
            ],
            options={
                "verbose_name": "پایه تحصیلی",
                "verbose_name_plural": "پایه\u200cهای تحصیلی",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SubjectModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام درس")),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="کد درس"),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
            ],
            options={
                "verbose_name": "درس",
                "verbose_name_plural": "دروس",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ClassroomModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام کلاس")),
                ("code", models.CharField(max_length=30, verbose_name="کد کلاس")),
                (
                    "capacity",
                    models.PositiveIntegerField(default=30, verbose_name="ظرفیت کلاس"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "فعال"),
                            ("inactive", "غیرفعال"),
                            ("completed", "پایان\u200cیافته"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classrooms",
                        to="academic.academicyearmodel",
                        verbose_name="سال تحصیلی",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classrooms",
                        to="academic.grademodel",
                        verbose_name="پایه",
                    ),
                ),
            ],
            options={
                "verbose_name": "کلاس",
                "verbose_name_plural": "کلاس\u200cها",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="StudentEnrollmentModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "فعال"),
                            ("completed", "تکمیل\u200cشده"),
                            ("cancelled", "لغوشده"),
                            ("transferred", "انتقال\u200cیافته"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="وضعیت ثبت\u200cنام",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ ثبت\u200cنام"
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_enrollments",
                        to="academic.classroommodel",
                        verbose_name="کلاس",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="student.studentmodel",
                        verbose_name="دانش\u200cآموز",
                    ),
                ),
            ],
            options={
                "verbose_name": "ثبت\u200cنام دانش\u200cآموز",
                "verbose_name_plural": "ثبت\u200cنام\u200cهای دانش\u200cآموزان",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ScheduleSessionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                (
                    "weekday",
                    models.CharField(
                        choices=[
                            ("saturday", "شنبه"),
                            ("sunday", "یکشنبه"),
                            ("monday", "دوشنبه"),
                            ("tuesday", "سه\u200cشنبه"),
                            ("wednesday", "چهارشنبه"),
                            ("thursday", "پنجشنبه"),
                            ("friday", "جمعه"),
                        ],
                        max_length=20,
                        verbose_name="روز هفته",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="زمان شروع")),
                ("end_time", models.TimeField(verbose_name="زمان پایان")),
                (
                    "session_number",
                    models.PositiveSmallIntegerField(verbose_name="شماره جلسه"),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_sessions",
                        to="academic.classroommodel",
                        verbose_name="کلاس",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_sessions",
                        to="teacher.teachermodel",
                        verbose_name="معلم",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_sessions",
                        to="academic.subjectmodel",
                        verbose_name="درس",
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسه برنامه هفتگی",
                "verbose_name_plural": "جلسات برنامه هفتگی",
                "ordering": ("weekday", "session_number"),
            },
        ),
    ]
