# Generated by Django 6.1.1 on 2026-10-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grademodel",
            name="description",
        ),
        migrations.AlterField(
            model_name="academicyearmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "در حال برنامه\u200cریزی"),
                    ("active", "فعال"),
                    ("completed", "پایان\u200cیافته"),
                ],
                default="planned",
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
    ]
