# Generated by Django 6.1.1 on 2026-10-01 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0002_remove_grademodel_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grademodel",
            name="academic_year",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grades",
                to="academic.academicyearmodel",
                verbose_name="سال تحصیلی",
            ),
            preserve_default=False,
        ),
    ]
