# Generated by Django 6.1.1 on 2026-10-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0003_grademodel_academic_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroommodel",
            name="grade",
            field=models.CharField(
                choices=[("Seven", "هفتم"), ("Eight", "هشتم"), ("Nine", "نهم")],
                default="Seven",
                max_length=20,
                verbose_name="پایه",
            ),
        ),
        migrations.DeleteModel(
            name="GradeModel",
        ),
    ]
