# Generated by Django 6.1.1 on 2026-10-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_alter_classroommodel_grade_delete_grademodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroommodel",
            name="code",
        ),
    ]
