# Generated by Django 6.1.1 on 2026-10-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0005_remove_classroommodel_code"),
        ("student", "0003_delete_studentnotemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroommodel",
            name="student",
            field=models.ManyToManyField(
                blank=True,
                related_name="classrooms",
                to="student.studentmodel",
                verbose_name="دانش آموزان",
            ),
        ),
        migrations.DeleteModel(
            name="StudentEnrollmentModel",
        ),
    ]
