# Generated by Django 6.1.1 on 2026-10-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0006_classroommodel_student_delete_studentenrollmentmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classroommodel",
            old_name="student",
            new_name="students",
        ),
    ]
