# Generated by Django 6.1.1 on 2026-10-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0007_rename_student_classroommodel_students"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedulesessionmodel",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="schedulesessionmodel",
            name="start_time",
        ),
        migrations.AlterField(
            model_name="schedulesessionmodel",
            name="session_number",
            field=models.PositiveSmallIntegerField(verbose_name="شماره زنگ"),
        ),
    ]
