# Generated by Django 6.1.1 on 2026-09-22 11:59

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        ("student", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DisciplineTypeModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="عنوان"),
                ),
                (
                    "effect",
                    models.CharField(
                        choices=[("positive", "مثبت"), ("negative", "منفی")],
                        max_length=20,
                        verbose_name="نوع اثر",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "نوع انضباطی",
                "verbose_name_plural": "انواع انضباطی",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="BehavioralEvaluationModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                ("evaluation_date", models.DateField(verbose_name="تاریخ ارزیابی")),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان ارزیابی"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("excellent", "عالی"),
                            ("good", "خوب"),
                            ("average", "متوسط"),
                            ("weak", "ضعیف"),
                        ],
                        max_length=20,
                        verbose_name="سطح ارزیابی",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="behavioral_evaluations",
                        to="academic.classroommodel",
                        verbose_name="کلاس",
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="behavioral_evaluations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ارزیابی\u200cکننده",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="behavioral_evaluations",
                        to="student.studentmodel",
                        verbose_name="دانش\u200cآموز",
                    ),
                ),
            ],
            options={
                "verbose_name": "ارزیابی رفتاری",
                "verbose_name_plural": "ارزیابی\u200cهای رفتاری",
                "ordering": ("-evaluation_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="DisciplineRecordModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discipline_records",
                        to="academic.classroommodel",
                        verbose_name="کلاس",
                    ),
                ),
                (
                    "recorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discipline_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت\u200cکننده",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discipline_records",
                        to="student.studentmodel",
                        verbose_name="دانش\u200cآموز",
                    ),
                ),
                (
                    "discipline_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="discipline.disciplinetypemodel",
                        verbose_name="نوع انضباطی",
                    ),
                ),
            ],
            options={
                "verbose_name": "سابقه انضباطی",
                "verbose_name_plural": "سوابق انضباطی",
                "ordering": ("-date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="EducationalRecordModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("cultural", "فرهنگی"),
                            ("religious", "مذهبی"),
                            ("sports", "ورزشی"),
                            ("social", "اجتماعی"),
                            ("competition", "مسابقه"),
                            ("responsibility", "مسئولیت"),
                            ("award", "تقدیر"),
                            ("other", "سایر"),
                        ],
                        max_length=30,
                        verbose_name="نوع سابقه",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("date", models.DateField(verbose_name="تاریخ")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="educational_records",
                        to="academic.classroommodel",
                        verbose_name="کلاس",
                    ),
                ),
                (
                    "recorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="educational_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت\u200cکننده",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="educational_records",
                        to="student.studentmodel",
                        verbose_name="دانش\u200cآموز",
                    ),
                ),
            ],
            options={
                "verbose_name": "سابقه تربیتی",
                "verbose_name_plural": "سوابق تربیتی",
                "ordering": ("-date", "-created_at"),
            },
        ),
    ]
