# Generated by Django 6.1.1 on 2026-09-22 12:39

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0001_initial"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=14, verbose_name="مبلغ پرداخت"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "نقدی"),
                            ("card_to_card", "کارت به کارت"),
                            ("gateway", "درگاه پرداخت"),
                        ],
                        max_length=20,
                        verbose_name="روش پرداخت",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("paid", "پرداخت شده"),
                            ("failed", "ناموفق"),
                            ("cancelled", "لغو شده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت پرداخت",
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="شناسه درگاه"
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="کد پیگیری"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پرداخت"
                    ),
                ),
                (
                    "expire_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان انقضا"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "installment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_transactions",
                        to="finance.tuitioninstallmentmodel",
                        verbose_name="قسط",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="student.studentmodel",
                        verbose_name="دانش\u200cآموز",
                    ),
                ),
                (
                    "tuition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_transactions",
                        to="finance.tuitionmodel",
                        verbose_name="شهریه",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت",
                "verbose_name_plural": "پرداخت\u200cها",
                "ordering": ("-created_at",),
            },
        ),
    ]
