# Generated by Django 6.1.1 on 2026-09-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmodel",
            name="card_pan",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="کارت"
            ),
        ),
        migrations.AddField(
            model_name="paymentmodel",
            name="ref_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="آیدی"
            ),
        ),
    ]
