# Generated by Django 6.1.1 on 2026-09-22 13:03

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Time"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Is Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted Time"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("system", "سیستمی"),
                            ("admin_alert", "اعلان مدیر"),
                            ("tuition_reminder", "یادآوری شهریه"),
                            ("tuition_payment", "پرداخت شهریه"),
                            ("educational", "آموزشی"),
                            ("attendance", "حضور و غیاب"),
                            ("discipline", "انضباطی"),
                            ("general", "عمومی"),
                        ],
                        max_length=50,
                        verbose_name="نوع اعلان",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("sms", "پیامک"),
                            ("in_app", "داخل سامانه"),
                            ("email", "ایمیل"),
                        ],
                        default="in_app",
                        max_length=50,
                        verbose_name="کانال ارسال",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان اعلان")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="متن اعلان"),
                ),
                (
                    "kwargs",
                    models.JSONField(
                        blank=True, null=True, verbose_name="اطلاعات اضافی"
                    ),
                ),
                (
                    "send_notify",
                    models.BooleanField(default=True, verbose_name="ارسال اعلان"),
                ),
                (
                    "is_showing",
                    models.BooleanField(default=True, verbose_name="نمایش اعلان"),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="گیرنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "اعلان",
                "verbose_name_plural": "اعلان\u200cها",
                "ordering": ("-created_at",),
            },
        ),
    ]
